# Generated by Django 5.0 on 2023-12-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='details_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
