# Generated by Django 5.0 on 2023-12-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_fooditem_details_url_fooditem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
