# Generated by Django 5.0 on 2023-12-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
